version: '3.3'
services:
  yarn: &yarn
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/app:delegated
      - ./node_modules:/app/node_modules
    working_dir: /app
    tty: true
    ports:
      - 3000:3000
    entrypoint: init
  firebase:
    image: andreysenov/firebase-tools
    volumes:
      - firebase-vollume:/home/node
    ports:
      - 4000:4000 # Emulator Suite UI
      - 5000:5000 # Firebase Hosting
      - 5001:5001 # Clound Functions
      - 8080:8080 # Cloud Firestore
      - 8085:8085 # Cloud Pub/Sub
      - 9000:9000 # Realtime Database
      - 9005:9005	# Firebase Login
      - 9099:9099 # Firebase Authentiation
      - 9199:9199 # Cloud Storage
    # working_dir: /opt/firebase
    command: "firebase emulators:start"
    tty: true
volumes:
  firebase-volume: