version: '3.3'
services:
  firebase:
    image: andreysenov/firebase-tools
    volumes:
      - ./.firebaserc:/firebase/.firebaserc
      - ./database.rules.json:/firebase/database.rules.json
      - ./firebase.json:/firebase/firebase.json
      - ./firestore.rules:/firebase/firestore.rules
      - ./firestore.indexes.json:/firebase/firestore.indexes.json
      - ./remoteconfig.template.json:/firebase/remoteconfig.template.json
      - ./storage.rules:/firebase/storage.rules
      - ./functions:/firebase/functions
      - ./database-debug.log:/firebase/database-debug.log
      - ./firestore-debug.log:/firebase/firestore-debug.log
      - ./pubsub-debug.log:/firebase/pubsub-debug.log
      - ./ui-debug.log:/firebase/ui-debug.log
      - firebase-volume:/home/node
    ports:
      - 4000:4000 # Emulator Suite UI
      - 5000:5000 # Firebase Hosting
      - 5001:5001 # Clound Functions
      - 8080:8080 # Cloud Firestore
      - 8085:8085 # Cloud Pub/Sub
      - 9000:9000 # Realtime Database
      - 9005:9005	# Firebase Login
      - 9099:9099 # Firebase Authentiation
      - 9199:9199 # Cloud Storage
    working_dir: /firebase
    tty: true
volumes:
  firebase-volume: